version: "3"

services:
  app:
    build: .
    container_name: app
    command: python main.py
    volumes:
      - .:/app
    depends_on:
      - postgres_database

  postgres_database:
    image: postgres
    environment:
      - POSTGRES_DB=autoria_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: docker_postgres
    volumes:
      - local_pgdata:/var/lib/postgresql/data/

volumes:
  local_pgdata: