version: "3"

services:
  app:
    build: .
    container_name: app
    command: python main.py
    volumes:
      - .:/app
    depends_on:
      - postgres_database

  postgres_database:
    image: postgres:15
    env_file:
      - .env.example
    container_name: docker_postgres
    volumes:
      - local_pgdata:/var/lib/postgresql/data/

volumes:
  local_pgdata: